// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CountdownBtn: typeof import('./components/button/countdown-btn.vue')['default']
    DataCourse: typeof import('./components/data/course/data-course.vue')['default']
    DataCourseAdmin: typeof import('./components/data/course/data-course-admin.vue')['default']
    DataCourseIndex: typeof import('./components/data/course/data-course-index.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    HeaderBase: typeof import('./components/layouts/header/header-base.vue')['default']
    HeaderLogin: typeof import('./components/layouts/header/header-login.vue')['default']
    LiveChat: typeof import('./components/live/chat/live-chat.vue')['default']
    LiveUsers: typeof import('./components/live/user/live-users.vue')['default']
    PieChart: typeof import('./components/echarts/PieChart.vue')['default']
    PreviewHtml: typeof import('./components/table/editor/preview-html.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rtc: typeof import('./components/webrtc/Rtc.vue')['default']
    RtcPublish: typeof import('./components/live/RtcPublish.vue')['default']
    SideBase: typeof import('./components/layouts/side/side-base.vue')['default']
    SideLogin: typeof import('./components/layouts/side/side-login.vue')['default']
    TableCourse: typeof import('./components/table/course/table-course.vue')['default']
    TableFile: typeof import('./components/table/file/table-file.vue')['default']
    TableFileAdmin: typeof import('./components/table/file/table-file-admin.vue')['default']
    TableJob: typeof import('./components/table/file/table-job.vue')['default']
    TableJobAdmin: typeof import('./components/table/file/table-job-admin.vue')['default']
    TablePlayback: typeof import('./components/table/video/table-playback.vue')['default']
    TablePlaybackAdmin: typeof import('./components/table/video/table-playback-admin.vue')['default']
    TableUser: typeof import('./components/table/user/table-user.vue')['default']
    TableUserAdmin: typeof import('./components/table/user/table-user-admin.vue')['default']
    Timing: typeof import('./components/tools/time/Timing.vue')['default']
    ToolClassStu: typeof import('./components/live/tool/tool-class-stu.vue')['default']
    ToolClassTea: typeof import('./components/live/tool/tool-class-tea.vue')['default']
    ToolNoteShort: typeof import('./components/tools/tool-note-short.vue')['default']
    VideoRtc: typeof import('./components/webrtc/VideoRtc.vue')['default']
    Webrtc: typeof import('./components/JSWebrtc/Webrtc.vue')['default']
  }
}

export {}
