base_path = "/root/data/record"
ffmpeg_path = "/root/conf/ffmpeg"
[minio]
endpoint = "minio:9000"
access_key_id = ""
secret_access_key = ""
use_ssl = false
bucket = "cloud-class"
base_url = "http://localhost:9000/"
[redis]
addr = "redis:6379"
db = 0
secure = false
pwd = ""